version: "3.1"

services:

  mongodb:
    image: "mongo:3.6"
    ports:
      - "27017:27017"
    restart: "always"
    command: --smallfiles
#    environment:
#      MONGO_INITDB_ROOT_USERNAME: "root"
#      MONGO_INITDB_ROOT_PASSWORD: "root"